spring.application.name=sample-app
spring.profiles.active=chaos-monkey
management.endpoints.web.exposure.include=chaosmonkey
management.endpoint.chaosmonkey.enabled=true

chaos.monkey.enabled=true
chaos.monkey.watcher.rest-controller=true
chaos.monkey.watcher.service=true
