spring.application.name=sample-app
spring.profiles.active=chaos-monkey
management.endpoints.web.exposure.include=chaosmonkey,health
management.endpoint.chaosmonkey.enabled=true

chaos.monkey.enabled=true
chaos.monkey.watcher.rest-controller=false
chaos.monkey.watcher.service=false
chaos.monkey.watcher.rest-template=true

external.api.base-url=http://localhost:8081

# Resilience4j properties
resilience4j.circuitbreaker.instances.externalApi.slidingWindowSize=2
resilience4j.circuitbreaker.instances.externalApi.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.externalApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.externalApi.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.externalApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.externalApi.recordExceptions=java.lang.Exception,java.lang.RuntimeException,java.util.concurrent.TimeoutException

resilience4j.retry.instances.externalApi.maxAttempts=3
resilience4j.retry.instances.externalApi.waitDuration=100ms

resilience4j.timelimiter.instances.externalApi.timeoutDuration=500ms
