spring.application.name=couchbase-sample-app

# Enable Java 21 Virtual Threads for Spring Boot handling Tomcat HTTP Requests
spring.threads.virtual.enabled=true

# Couchbase Default configuration (can be overridden by environment variables or Testcontainers)
couchbase.connectionString=127.0.0.1
couchbase.username=Administrator
couchbase.password=password
couchbase.bucketName=sample_bucket
